name: Issue Comment (Reminder)

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    name: ğŸ‘€ Create reminder
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘€ check for reminder
        uses: agrc/create-reminder-action@v1
